#!/bin/sh
set -e

echo "Setup permissions"
chown -R karaoke-time:karaoke-time /var/lib/karaoke

echo "Activate ruby version and installing gems"
sudo -u karaoke-time bash <<'EOF'
  cd ~
  source ~/.bashrc
  bin/mise install
  gem install bundler:2.5.6 --install-dir ~/.local/share/gem/ruby/3.1.0
  bin/bundle config set --local path vendor/bundle
  RAILS_ENV=production bin/bundle install
EOF

echo "Setup the database"
sudo -u karaoke-time bash <<'EOF'
  cd ~
  source ~/.bashrc
  export RAILS_ENV=production
  bin/rails credentials:edit
  bin/rails db:create
  bin/rails db:migrate
  bin/rails assets:precompile
EOF

echo "Download the latest version of yt-dlp"
sudo -u karaoke-time bash <<'EOF'
  cd ~
  source ~/.bashrc
  export RAILS_ENV=production
  bin/rails r 'YtDlpManager.update_binary'
EOF

if ! systemctl is-enabled --quiet karaoke-time.service; then
  echo "Enabling the service"
  systemctl enable karaoke-time.service
fi

systemctl daemon-reload

if systemctl is-active --quiet karaoke-time.service; then
  echo "Restarting the service"
  systemctl restart karaoke-time.service
else
  echo "Starting the service"
  systemctl start karaoke-time.service
fi

exit 0
